#!/bin/bash

# This allows the user to pass in a ENV EXTERNAL_HOST and set it to an external IP

PRESENT_OPTS="-http=0.0.0.0:3999"
if [ -n $EXTERNAL_HOST ]; then
        PRESENT_OPTS="-orighost=$EXTERNAL_HOST $PRESENT_OPTS"
fi
PRESENT_BASE="-base=/base"

present $PRESENT_OPTS $PRESENT_BASE
